import type { CreatureDef } from "./types";

export const CREATURE_DEFS: CreatureDef[] = [
  {
    id: "moss-bullfrog",
    name: "Moss-Crowned Bullfrog",
    lore: "Old bayou folks say this bullfrog grows a living crown of Spanish moss and sings only at first light. Catch its amber eyes and it may croak your true name.",
    sprite: "/sprites/creature-1.png",
    radius: 22,
    speed: 28,
    behavior: "shy",
    appearFrom: 0,
    appearTo: 0.55,
    docRange: 58,
    danger: 0,
    rarity: "common",
    color: "#6b9e3e",
  },
  {
    id: "crawfish",
    name: "Mudbug Crawfish",
    lore: "Louisiana’s little red royalty. They dig chimney mounds in soft mud and boil into every good story told around a picnic table.",
    sprite: "/sprites/crawfish.png",
    radius: 11,
    speed: 14,
    behavior: "shy",
    appearFrom: 0,
    appearTo: 0.85,
    docRange: 88,
    danger: 0,
    rarity: "common",
    color: "#d04030",
  },
  {
    id: "slider-turtle",
    name: "Red-Eared Slider",
    lore: "Sun-basker of every quiet log. Slide off into blackwater at the first footstep — patience gets the page in your journal.",
    sprite: "/sprites/turtle.png",
    radius: 11,
    speed: 16,
    behavior: "shy",
    appearFrom: 0.05,
    appearTo: 0.8,
    docRange: 64,
    danger: 0,
    rarity: "common",
    color: "#3a5a40",
  },
  {
    id: "nutria",
    name: "Bayou Nutria",
    lore: "Big orange-toothed coypu of the marsh. Not native, but fully Louisiana now — chewing canals and making wavelets at dusk.",
    sprite: "/sprites/nutria.png",
    radius: 11,
    speed: 44,
    behavior: "wander",
    appearFrom: 0.1,
    appearTo: 0.85,
    docRange: 56,
    danger: 0,
    rarity: "uncommon",
    color: "#8a7060",
  },
  {
    id: "egret",
    name: "Great Egret",
    lore: "Snow-white fisher of the shallows. Stands still as a cypress knee until a minnow forgets — then the spear-beak falls.",
    sprite: "/sprites/egret.png",
    radius: 10,
    speed: 38,
    behavior: "wander",
    appearFrom: 0,
    appearTo: 0.7,
    docRange: 58,
    danger: 0,
    rarity: "uncommon",
    color: "#f0f0e8",
  },
  {
    id: "ghost-gar",
    name: "Blue Ghost Gar",
    lore: "A gar that glows like flooded moonwater. Fishermen claim it swims through piers as if wood were fog — a warning before the big storms.",
    sprite: "/sprites/creature-2.png",
    radius: 26,
    speed: 55,
    behavior: "wander",
    appearFrom: 0.05,
    appearTo: 0.7,
    docRange: 62,
    danger: 0,
    rarity: "uncommon",
    color: "#2ec4b6",
  },
  {
    id: "mossy-gator",
    name: "Moss-Backed Alligator",
    lore: "Not quite ordinary: Spanish moss braids its snout and its eyes burn gold when hungry. Slow and heavy — give it room.",
    sprite: "/sprites/creature-3.png",
    radius: 30,
    speed: 14,
    behavior: "aggressive",
    appearFrom: 0.1,
    appearTo: 1,
    docRange: 70,
    danger: 10,
    rarity: "uncommon",
    color: "#3d6b3a",
  },
  {
    id: "feu-follet",
    name: "Feu Follet",
    lore: "Cajun will-o'-the-wisp. A pale green fire that lures the lost deeper into the cypress. Follow it only with your journal open.",
    sprite: "/sprites/creature-4.png",
    radius: 16,
    speed: 28,
    behavior: "drift",
    appearFrom: 0.18,
    appearTo: 1,
    docRange: 88,
    danger: 0,
    rarity: "rare",
    color: "#7ef0c0",
  },
  {
    id: "spirit-catfish",
    name: "Phantom Catfish",
    lore: "A catfish spirit of the deep channels. Translucent as bottle-glass, it appears when the sun leans west and the water goes still.",
    sprite: "/sprites/cryptid-3.png",
    radius: 24,
    speed: 42,
    behavior: "wander",
    appearFrom: 0.25,
    appearTo: 0.85,
    docRange: 60,
    danger: 0,
    rarity: "uncommon",
    color: "#9ee7ff",
  },
  {
    id: "lutin",
    name: "Bayou Lutin",
    lore: "A tiny swamp spirit in a leaf hat. Mischief-maker of sugarcane camps and pirogues — leave a crumb and it may dance instead of hide.",
    sprite: "/sprites/cryptid-4.png",
    radius: 14,
    speed: 22,
    behavior: "wander",
    appearFrom: 0.1,
    appearTo: 0.95,
    docRange: 92,
    danger: 0,
    rarity: "rare",
    color: "#c8e06c",
  },
  {
    id: "manchac-ghost",
    name: "Manchac Swamp Ghost",
    lore: "Spirit of Manchac — the Ghost Swamp. Some name her Julie Brown, the Creole songstress whose curse drowned Frenier. At dusk she drifts among the cypress.",
    sprite: "/sprites/manchac-ghost.png",
    radius: 26,
    speed: 38,
    behavior: "drift",
    appearFrom: 0.22,
    appearTo: 1,
    docRange: 64,
    danger: 0,
    rarity: "legendary",
    color: "#9ee8ff",
  },
  {
    id: "voodoo-woman",
    name: "Bayou Voodoo Woman",
    lore: "She walks with the scary ones after the light thins — headwrap, bone charms, a bottle that never empties the same way twice. Not all who document her leave with the same memory.",
    sprite: "/sprites/voodoo-woman.png",
    radius: 28,
    speed: 34,
    behavior: "haunt",
    appearFrom: 0.24,
    appearTo: 1,
    docRange: 68,
    danger: 12,
    rarity: "legendary",
    color: "#7a4a9a",
  },
  {
    id: "lafitte",
    name: "Jean Lafitte’s Phantom",
    lore: "Privateer ghost of the foggy channels. Tricorn and coat of river-mist — gold that never stays in a living hand. Fishermen tip their hats when the fog thickens wrong.",
    sprite: "/sprites/ghost-lafitte.png",
    radius: 28,
    speed: 40,
    behavior: "drift",
    appearFrom: 0.26,
    appearTo: 1,
    docRange: 66,
    danger: 0,
    rarity: "legendary",
    color: "#7ec8e8",
  },
  {
    id: "grunch",
    name: "Grunch Road Critter",
    lore: "Urban-legend cousin of the New Orleans edge — lanky, moss-stained, and too smart for a dog. Grunch Road stories end with missing pets and laughter that isn’t human.",
    sprite: "/sprites/cryptid-grunch.png",
    radius: 24,
    speed: 52,
    behavior: "shy",
    appearFrom: 0.28,
    appearTo: 1,
    docRange: 60,
    danger: 8,
    rarity: "legendary",
    color: "#8a7a40",
  },
  {
    id: "woman-white",
    name: "Woman in White",
    lore: "Southern Gothic visitor — white dress, empty eyes, patience of old houses. Not pure bayou, but the mist will carry a plantation ghost if the hollow opens a door.",
    sprite: "/sprites/ghost-woman-white.png",
    radius: 26,
    speed: 32,
    behavior: "drift",
    appearFrom: 0.28,
    appearTo: 1,
    docRange: 64,
    danger: 0,
    rarity: "legendary",
    color: "#e8e8f0",
  },
  {
    id: "letiche",
    name: "Letiche",
    lore: "Swamp-child legend — raised by alligators in the stories, left with pale eyes and wet hair. If it offers you a hand, check how many fingers the water counts.",
    sprite: "/sprites/letiche.png",
    radius: 22,
    speed: 44,
    behavior: "haunt",
    appearFrom: 0.26,
    appearTo: 1,
    docRange: 58,
    danger: 10,
    rarity: "legendary",
    color: "#a0b090",
  },
  {
    id: "rail-passenger",
    name: "Drowned Railroad Passenger",
    lore: "Tied to the Manchac line that the water took. Suitcase still in hand, train whistle that isn’t there. He walks the old grade when Ghost Hollow is listening.",
    sprite: "/sprites/ghost-passenger.png",
    radius: 26,
    speed: 30,
    behavior: "drift",
    appearFrom: 0.24,
    appearTo: 1,
    docRange: 66,
    danger: 0,
    rarity: "legendary",
    color: "#40d0e8",
  },
  {
    id: "pere-malfait",
    name: "Pete Malfait — Moss Man",
    lore: "Père Malfait — Father of Mischief, the Moss Man. A tall shape of Spanish moss and wet leaves with coal-fire eyes. After dark, the moss walks.",
    sprite: "/sprites/pere-malfait.png",
    radius: 38,
    speed: 36,
    behavior: "haunt",
    appearFrom: 0.3,
    appearTo: 1,
    docRange: 74,
    danger: 20,
    rarity: "legendary",
    color: "#5a8a3a",
  },
  {
    id: "rougarou",
    name: "Rougarou",
    lore: "The Cajun werewolf of the wetlands. Some say a curse; others a bargain. It prowls only after full dark.",
    sprite: "/sprites/cryptid-1.png",
    radius: 34,
    speed: 58,
    behavior: "haunt",
    appearFrom: 0.32,
    appearTo: 1,
    docRange: 72,
    danger: 24,
    rarity: "legendary",
    color: "#a09088",
  },
  {
    id: "honey-island",
    name: "Honey Island Swamp Monster",
    lore: "Louisiana's famous cryptid — tall, moss-furred, and smelling of wet cypress. Tracks appear in soft mud after storms.",
    sprite: "/sprites/cryptid-2.png",
    radius: 36,
    speed: 32,
    behavior: "aggressive",
    appearFrom: 0.34,
    appearTo: 1,
    docRange: 74,
    danger: 24,
    rarity: "legendary",
    color: "#6a7a62",
  },
];

export const CREATURE_BY_ID = Object.fromEntries(
  CREATURE_DEFS.map((d) => [d.id, d]),
) as Record<import("./types").CreatureId, CreatureDef>;
